#!/bin/bash

version_param="patch";
git_msg="";

if (( $# == 1 )); then
    if [[ "$1" == "maj" || "$1" == "major" || "$1" == "min" || "$1" == "minor" || "$1" == "patch" ]]; then
        version_param="$1";
    else
        git_msg="$1";
    fi
elif (( $# == 2 )); then
    if [[ "$1" == "maj" || "$1" == "major" || "$1" == "min" || "$1" == "minor" || "$1" == "patch" ]]; then
        version_param="$1";
        git_msg="$2";
    elif [[ "$2" == "maj" || "$2" == "major" || "$2" == "min" || "$2" == "minor" || "$2" == "patch" ]]; then
        version_param="$2";
        git_msg="$1";
    fi
fi

npm_publish_versionbump "$version_param";

if [[ "$git_msg" == "" ]]; then
    push;
else
    push "$git_msg";
fi